### ISSUE TITLE
Self-loops in edge labels

### ISSUE THREAD

**Issue by ClaudMor** [deezer/gravity_graph_autoencoders#12]
Hello,

I was wondering why do you add self-loops in the edge labels, as [this line](https://github.com/deezer/gravity_graph_autoencoders/blob/fa098943ad8b25de14882d76f3ad08253b30ab35/gravity_gae/train.py#L210) seems to suggest.

Thank you.

**Comment by GuillaumeSalhaGalvan** [comment]
Dear Claudio,

First of all, thank you for your message and interest in this work.

Indeed, as you correctly noticed, we add self-loops to the input graph. Equivalently, we add an identity matrix to the input adjacency matrix.

This is a common practice in the research and implementations related to GCN/GAE/VGAE models. For instance, this addition is explicitly mentioned in the original papers on these models ([here](https://arxiv.org/pdf/1611.07308.pdf%5D) and [there](https://arxiv.org/pdf/1609.02907.pdf)) by Kipf and Welling.

There are several ways to look at it:

- From the GCN encoder perspective: without self-loops, at each layer $l$, a node $i$ would obtain its embedding vector throught the aggregation of the embedding vectors* at layer $l-1$ of its direct neighbours. _With self-loops_, this same node $i$ would aggregate vectors from its direct neighbours _and itself_. Propagating the node's own representation is usually something we want to ensure faithful and stable representations.

- From the loss perspective: when computing the reconstruction loss, having $A_{ii} = 1$ instead of $A_{ii} = 0$ also helps avoid weird effects, where the model tries to force vectors _"not to be similar to themself"_ typically by skrinking theirs norms...

This is the intuition. If you are interested in the theoretical aspects, there are a number of papers that rigorously study the positive effects of self-loop additions on the accuracy, smoothness, and stability of the resulting node embedding representations. You can take a look at [this paper](https://arxiv.org/pdf/1902.07153.pdf) from Wu et al. for instance.

I hope this helps!

Best,

Guillaume


_*Or the input feature vectors, in the case of the first layer._

**Comment by ClaudMor** [comment]
Thank you very much for the detailed and referenced answer!

I'll close this issue since it has been solved.
